### PR TITLE
Updated master

### PR DESCRIPTION
**Pull request by iwankgb**
Updates master with changes introduces in 2020. Related to https://github.com/golangci/golangci-lint/issues/1495

@golangci/team, I summon you.

### CODE REVIEW

**Comment by iwankgb** [comment]
Or even @golangci/core-team as @golangci/team seems to miss privileges to merge it.

**Comment by ernado** [comment]
@jirfag I can't merge this even on behalf of the @golangci/core-team :(

**Comment by iwankgb** [comment]
This is some serious black magic. It makes me think that we should work with liter maintainers to enable library usage in the upstream. There are more similar forks here and I guess we can't merge PRs to them either.

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by iwankgb** [comment]
We should be able to use upstream version now: https://github.com/jgautheron/goconst/commit/ce0d7c014a65a9555788fbfb8ee5086ad9885ccd

**Comment by ernado** [comment]
Great! 
Please link MR/issue of switching to goconst upstream here :)

I hope that we will eventually switch to upstream all our forks.

**Comment by iwankgb** [comment]
Replacing fork with upstream PR: https://github.com/golangci/golangci-lint/pull/1500

**Pull request closed without merging**
